config/routes.rb
Rails.application.routes.draw do      
 
  resources :payment_terms
  root 'mains#index'

  # teacher
  get                  'admin/teachers'  => 'teachers#index'
  get              'admin/teachers/new'  => 'teachers#new'
  get          'admin/edit-teacher/:id'  => 'teachers#edit'
  get               'admin/teachers/:id' => 'teachers#destroy'

  get       'teachers/qualification/:id' => 'teacher_qualifications#destroy'
  get          'teachers/background/:id' => 'teacher_backgrounds#destroy'

  # sensei-preview
  get                           'sensei' => 'senseis#index'
  
  # inquiry
  get                  'admin/inquiries' => 'inquiries#show'
  get                          'inquiry' => 'inquiries#index'

  # manila
  get                 'manila/dashboard' => 'manilascheds#index'  
  get              'manila/new_schedule' => 'manilascheds#new'   
  get         'manila/edit-schedule/:id' => 'manilascheds#edit'
  patch     'manila/update-schedule/:id' => 'manilascheds#update'
  get       'manila/delete-schedule/:id' => 'manilascheds#destroy'

  # submanilasched
  get              'manila/schedule/:id' => 'manila_sub_scheds#new'  
  get         'manila/schedule/edit/:id' => 'manila_sub_scheds#edit'
  get     '  manila/schedule/delete/:id' => 'manila_sub_scheds#destroy' 
  patch     'manila/schedule/update/:id' => 'manila_sub_scheds#update'

  # manila students
  get 'manila-schedule/edit-student/:id' => 'manila_students#edit'    
  get         'manila-schedules/:id/:id' => 'manila_students#new'      
  get              'manila-students/:id' => 'manila_students#show_manila_students'
  get        'delete-manila-student/:id' => 'manila_students#destroy' 

  # cebu
  get                   'cebu/dashboard' => 'cebuscheds#index'  
  get                'cebu/new_schedule' => 'cebuscheds#new'   
  get           'cebu/edit-schedule/:id' => 'cebuscheds#edit'
  patch       'cebu/update-schedule/:id' => 'cebuscheds#update'
  get         'cebu/delete-schedule/:id' => 'cebuscheds#destroy' 

  # subcebusched
  get                'cebu/schedule/:id' => 'cebu_sub_scheds#new'  
  get           'cebu/schedule/edit/:id' => 'cebu_sub_scheds#edit'
  get         'cebu/schedule/delete/:id' => 'cebu_sub_scheds#destroy' 
  patch       'cebu/schedule/update/:id' => 'cebu_sub_scheds#update'

  # cebu students
  get           'cebu-students/edit/:id' => 'cebu_students#edit'    
  get           'cebu-schedules/:id/:id' => 'cebu_students#new'     
  get                'cebu-students/:id' => 'cebu_students#show_cebu_students'
  get          'delete-cebu-student/:id' => 'cebu_students#destroy' 

  # articles admin
  get                  'admin/articles/' => 'articles#index'
  get               'admin/articles/new' => 'articles#new'
  get               'admin/articles/:id' => 'articles#show'
  get          'admin/articles/:id/edit' => 'articles#edit'
  delete     'admin/articles/:id/delete' => 'articles#delete'
  mount                 Ckeditor::Engine => '/ckeditor'

  # articles main
  get                        '/articles' => 'main_articles#index'
  get                     'articles/:id' => 'main_articles#show'

  # main dashboards
  get                  'admin/dashboard' => 'dashboards#index'

  # main
  get                'all-payment-terms' => 'mains#payment_terms'
  get                   'cebu-schedules' => 'mains#cebuschedule'
  get               'cebu-schedules/:id' => 'mains#show_cebu'
  get                 'manila-schedules' => 'mains#manilaschedule'
  get             'manila-schedules/:id' => 'mains#show_manila'
  get              'reservation-success' => 'mains#success'
  get                  'student-gallery' => 'mains#gallery'
 
  # sessions
  get                           "logout" => "sessions#destroy"
  get                       'ncrs/login' => 'sessions#new'
  get                     'ncrs/sign_up' => 'admins#new'

  resources :sessions
  resources :admins 
  resources :password_resets 

  # teachers information
  resources :teachers
  resources :teacher_qualifications
  resources :teacher_backgrounds
  resources :senseis

  # articles
  resources :articles

  # gallery 
  resources :galleries

  # cebu
  resources :cebuscheds 
  resources :cebu_sub_scheds 

  # manila
  resources :manilascheds 
  resources :manila_sub_scheds 

  # inquiry
  resources :inquiries

  # cebu students
  resources :cebu_students

  # manila students
  resources :manila_students

  # main
  resources :mains
 
end

app/models/payment_term.rb
class PaymentTerm < ActiveRecord::Base
end

app/controllers/payment_terms_controller.rb
class PaymentTermsController < ApplicationController
  before_action :set_payment_term, only: [:show, :edit, :update, :destroy]

  # GET /payment_terms
  # GET /payment_terms.json
  def index
    @payment_terms = PaymentTerm.all
  end

  # GET /payment_terms/1
  # GET /payment_terms/1.json
  def show
  end

  # GET /payment_terms/new
  def new
    @payment_term = PaymentTerm.new
  end

  # GET /payment_terms/1/edit
  def edit
  end

  # POST /payment_terms
  # POST /payment_terms.json
  def create
    @payment_term = PaymentTerm.new(payment_term_params)

    respond_to do |format|
      if @payment_term.save
        format.html { redirect_to @payment_term, notice: 'Payment term was successfully created.' }
        format.json { render :show, status: :created, location: @payment_term }
      else
        format.html { render :new }
        format.json { render json: @payment_term.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payment_terms/1
  # PATCH/PUT /payment_terms/1.json
  def update
    respond_to do |format|
      if @payment_term.update(payment_term_params)
        format.html { redirect_to @payment_term, notice: 'Payment term was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment_term }
      else
        format.html { render :edit }
        format.json { render json: @payment_term.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_terms/1
  # DELETE /payment_terms/1.json
  def destroy
    @payment_term.destroy
    respond_to do |format|
      format.html { redirect_to payment_terms_url, notice: 'Payment term was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_term
      @payment_term = PaymentTerm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_term_params
      params.require(:payment_term).permit(:content)
    end
end

app/helpers/payment_terms_helper.rb
module PaymentTermsHelper
end

app/views/payment_terms/_form.html.erb
<%= form_for(@payment_term) do |f| %>
  <% if @payment_term.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment_term.errors.count, "error") %> prohibited this payment_term from being saved:</h2>

      <ul>
      <% @payment_term.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.cktext_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payment_terms/edit.html.erb
<% provide(:title, "Edit Payment Term |")%>
<%= render "layouts/navbar_admin" %> 
<div class="container">
	<h4>Edit Payment Term</h4>

	<%= render 'form' %>

	<%= link_to 'Show', @payment_term %> |
	<%= link_to 'Back', payment_terms_path %>
</div>  

app/views/payment_terms/index.html.erb
<% provide(:title, "Payment Terms |")%>
<%= render "layouts/navbar_admin" %> 
<div class="container">
  <h4 class="center">All Payment Terms</h4>

  <div class="fixed-action-btn">
    <%= link_to material_icon.add, new_payment_term_path, :class => "waves-effect waves-light btn-floating btn-large blue"%> 
  </div>   
  
  <p class="center teal-text"><%= notice %></p>
  
  <% if @payment_terms.count == 0 %>
    <h4 class="red-text center">No Terms added!</h4>
  <% else %>
    <% @payment_terms.each do |payment_term| %>
      <div class="row"> 
        <div class="col s12"> 
            <%= raw payment_term.content %> 
          <p class="right">
            <%= link_to 'Show', payment_term %> | 
            <%= link_to 'Edit', edit_payment_term_path(payment_term) %> |
            <%= link_to 'Destroy', payment_term, method: :delete, data: { confirm: 'Are you sure?' } %>
          </p>
        </div>
      </div>
      <div class="divider"></div>
    <% end %>  
  <% end %>

</div> 

app/views/payment_terms/new.html.erb
<% provide(:title, "New Payment Term |")%>
<%= render "layouts/navbar_admin" %> 
<div class="container">
	<h4>New Payment Term</h4>

	<%= render 'form' %>

	<%= link_to 'Back', payment_terms_path %>
</div> 

app/views/payment_terms/show.html.erb
<% provide(:title, "New Payment Term |")%>
<%= render "layouts/navbar_admin" %> 
<div class="container">
  	<p class="center teal-text"><%= notice %></p>
		<p>
		  <strong>Content:</strong>
		  <%= raw @payment_term.content %>
		</p> 

		<%= link_to 'Edit', edit_payment_term_path(@payment_term) %> |
		<%= link_to 'Back', payment_terms_path %>

</div> 