config/routes.rb
Rails.application.routes.draw do      
 
  resources :payment_terms
  root 'mains#index'

  # teacher
  get                  'admin/teachers'  => 'teachers#index'
  get              'admin/teachers/new'  => 'teachers#new'
  get          'admin/edit-teacher/:id'  => 'teachers#edit'
  get               'admin/teachers/:id' => 'teachers#destroy'

  get       'teachers/qualification/:id' => 'teacher_qualifications#destroy'
  get          'teachers/background/:id' => 'teacher_backgrounds#destroy'

  # sensei-preview
  get                           'sensei' => 'senseis#index'
  
  # inquiry
  get                  'admin/inquiries' => 'inquiries#show'
  get                          'inquiry' => 'inquiries#index'

  # manila
  get                 'manila/dashboard' => 'manilascheds#index'  
  get              'manila/new_schedule' => 'manilascheds#new'   
  get         'manila/edit-schedule/:id' => 'manilascheds#edit'
  patch     'manila/update-schedule/:id' => 'manilascheds#update'
  get       'manila/delete-schedule/:id' => 'manilascheds#destroy'

  # submanilasched
  get              'manila/schedule/:id' => 'manila_sub_scheds#new'  
  get         'manila/schedule/edit/:id' => 'manila_sub_scheds#edit'
  get     '  manila/schedule/delete/:id' => 'manila_sub_scheds#destroy' 
  patch     'manila/schedule/update/:id' => 'manila_sub_scheds#update'

  # manila students
  get 'manila-schedule/edit-student/:id' => 'manila_students#edit'    
  get         'manila-schedules/:id/:id' => 'manila_students#new'      
  get              'manila-students/:id' => 'manila_students#show_manila_students'
  get        'delete-manila-student/:id' => 'manila_students#destroy' 

  # cebu
  get                   'cebu/dashboard' => 'cebuscheds#index'  
  get                'cebu/new_schedule' => 'cebuscheds#new'   
  get           'cebu/edit-schedule/:id' => 'cebuscheds#edit'
  patch       'cebu/update-schedule/:id' => 'cebuscheds#update'
  get         'cebu/delete-schedule/:id' => 'cebuscheds#destroy' 

  # subcebusched
  get                'cebu/schedule/:id' => 'cebu_sub_scheds#new'  
  get           'cebu/schedule/edit/:id' => 'cebu_sub_scheds#edit'
  get         'cebu/schedule/delete/:id' => 'cebu_sub_scheds#destroy' 
  patch       'cebu/schedule/update/:id' => 'cebu_sub_scheds#update'

  # cebu students
  get           'cebu-students/edit/:id' => 'cebu_students#edit'    
  get           'cebu-schedules/:id/:id' => 'cebu_students#new'     
  get                'cebu-students/:id' => 'cebu_students#show_cebu_students'
  get          'delete-cebu-student/:id' => 'cebu_students#destroy' 

  # articles admin
  get                  'admin/articles/' => 'articles#index'
  get               'admin/articles/new' => 'articles#new'
  get               'admin/articles/:id' => 'articles#show'
  get          'admin/articles/:id/edit' => 'articles#edit'
  delete     'admin/articles/:id/delete' => 'articles#delete'
  mount                 Ckeditor::Engine => '/ckeditor'

  # articles main
  get                        '/articles' => 'main_articles#index'
  get                     'articles/:id' => 'main_articles#show'

  # main dashboards
  get                  'admin/dashboard' => 'dashboards#index'

  # main
  get                'all-payment-terms' => 'mains#payment_terms'
  get                   'cebu-schedules' => 'mains#cebuschedule'
  get               'cebu-schedules/:id' => 'mains#show_cebu'
  get                 'manila-schedules' => 'mains#manilaschedule'
  get             'manila-schedules/:id' => 'mains#show_manila'
  get              'reservation-success' => 'mains#success'
  get                  'student-gallery' => 'mains#gallery'
 
  # sessions
  get                           "logout" => "sessions#destroy"
  get                       'ncrs/login' => 'sessions#new'
  get                     'ncrs/sign_up' => 'admins#new'

  resources :sessions
  resources :admins 
  resources :password_resets 

  # teachers information
  resources :teachers
  resources :teacher_qualifications
  resources :teacher_backgrounds
  resources :senseis

  # articles
  resources :articles

  # gallery 
  resources :galleries

  # cebu
  resources :cebuscheds 
  resources :cebu_sub_scheds 

  # manila
  resources :manilascheds 
  resources :manila_sub_scheds 

  # inquiry
  resources :inquiries

  # cebu students
  resources :cebu_students

  # manila students
  resources :manila_students

  # main
  resources :mains
 
end

app/models/manila_sub_sched.rb
class ManilaSubSched < ActiveRecord::Base
  belongs_to :manila_sched 

  validates_presence_of :manila_sched_id, :admin_id, :ms_day, :ms_session, :ms_time, :ms_jlpt_level, :ms_status, :ms_slots

  extend FriendlyId 
	friendly_id :ms_day, use: :slugged  

   	def should_generate_new_friendly_id?
	    slug.blank? || self.ms_day_changed?
	end 
end

app/controllers/manila_sub_scheds_controller.rb
class ManilaSubSchedsController < ApplicationController
  before_action :require_user 
 
  def new  
    @manilasched = ManilaSched.friendly.find(params[:id])
    @showsubsched = ManilaSubSched.where(:manila_sched_id => @manilasched).order(created_at: :desc)
    @subschedule = ManilaSubSched.new 
    @manilastudents = ManilaStudent.all.order(created_at: :desc)
  end

  def show
    @manilasched = ManilaSched.friendly.all
    @manilasubsched = ManilaSubSched.friendly.find(params[:id])
  end
  
  def create
    @subschedule = ManilaSubSched.new(submanilasched_params)
    if @subschedule.save
      redirect_to :back, :notice => "New Sub-Schedule added Successfully"
    else
      redirect_to :back, :notice => "Error on Creating New Sub-Schedule"
    end
  end
  
  def edit    
    @getsubsched = ManilaSubSched.find(params[:id]) 
    @manilasched = ManilaSched.find(@getsubsched.manila_sched_id) 
  end  

  def update 
    @getsubsched = ManilaSubSched.find(params[:id])
      if @getsubsched.update_attributes(submanilasched_params)
        redirect_to :back, :notice => "Updated Sub-Schedule Successfully"
      else
        redirect_to :back, :notice => "Updating Sub-Schedule Failed"
      end
  end 

  def destroy
    @deleteschedule = ManilaSubSched.find(params[:id])
    if @deleteschedule.destroy
      redirect_to :back, :notice => "Deleted Sub-Schedule Successfully"
    else
      redirect_to :back, :notice => "Deleting Sub-Schedule Failed"
    end
  end  

  private

  def submanilasched_params 
    params.require(:manila_sub_sched).permit(:manila_sched_id, :admin_id, :ms_day, :ms_session, :ms_time, :ms_jlpt_level, :ms_status, :ms_starts, :ms_slots)
  end

end

app/helpers/manila_sub_scheds_helper.rb
module ManilaSubSchedsHelper
end

app/views/manila_sub_scheds/edit.html.erb
<%= render "layouts/navbar_admin" %> 
<div class="container"> 
	<div class="section">    

    	<%= form_for @getsubsched, url:{action: "update"}, html: {class: "form"} do |sub_sched| %>  
	      	<div class="row">
	      		<div class="col s1"></div>
	      		<div class="col s10"> 
	      		
					<%= render "partials/notification" %>

    				<h4 class="center">Add Sub Schedule for <br><span class="blue-text"><%= @getsubsched.ms_day.upcase %></span></h4> 

				      <div class="row">
				        <div class="input-field col s6"> 
				          <%= sub_sched.hidden_field :manila_sched_id, :value => @getsubsched.manila_sched_id, :class => "center" %>  
				        </div>
				        <div class="input-field col s6">
				          <%= sub_sched.hidden_field :admin_id, :value => current_user.id %>  
				        </div>
				      </div> 
				      <div class="row">
				        <div class="input-field col s3">
				          <%= sub_sched.label  :ms_slots, "Slots"%>
				          <%= sub_sched.text_field  :ms_slots, :class => "center"  %> 
				        </div>
				        <div class="input-field col s6">
				          <%= sub_sched.label  :ms_day, "Days"%>
				          <%= sub_sched.text_field  :ms_day, :class => "center"  %> 
				        </div>
				        <div class="input-field col s3">
				          <%= sub_sched.label  :ms_session, "Session"%>
				          <%= sub_sched.text_field  :ms_session, :class => "center"  %> 
				        </div>
				      </div>   
				      <div class="row">
				        <div class="input-field col s4">
				          <%= sub_sched.label  :ms_time, "Time"%>
				          <%= sub_sched.text_field  :ms_time, :class => "center"  %> 
				        </div>
				        <div class="input-field col s4">
				          <%= sub_sched.label  :ms_starts, "Class Starts"%>
				          <%= sub_sched.text_field  :ms_starts, :class => "center"  %> 
				        </div>
				        <div class="input-field col s4">
				          <%= sub_sched.label  :ms_jlpt_level, "JLPT Level"%>
				          <%= sub_sched.text_field :ms_jlpt_level, :class => "center"  %> 
				        </div>
				      </div>  
				      <div class="center">   
				          <%= sub_sched.label  :ms_status, "Status"%>
						    <%= sub_sched.radio_button(:ms_status, "0", :checked => true) %>
							<%= sub_sched.label(:ms_status_0, "Deactivate") %>
							<%= sub_sched.radio_button(:ms_status, "1") %>
							<%= sub_sched.label(:ms_status_1, "Activate") %>  
		              </div> 
	      			</div>   
	      		<div class="col s1"></div> 
	      	</div>  <br>
	      	<div class="center-align">
	      		<%= sub_sched.submit "Update Sub Schedule", :class => "waves-effect waves-light btn " %>
	      	</div>  
		<% end %> 
	</div> 
</div>
<div class="section">
	<div class="container">
		<%= link_to "Main dashboard", admin_dashboard_path %> > 
		<%= link_to "Manila Dashboard", manila_dashboard_path %> >  
		<%= link_to @manilasched.duration, "/manila/schedule/#{@manilasched.slug}"%> 
	</div>
</div>

app/views/manila_sub_scheds/new.html.erb
<% provide(:title, @manilasched.duration + " |") %>
<%= render "layouts/navbar_admin" %>    

	<!-- Subschedule --> 
    	<div class="container">
		  	<div id="sub_schedules" class="section scrollspy">
		  		<div class="section">
			        <h4 class="center blue-text"><%= @manilasched.duration.upcase %> <br><small class="grey-text">SCHEDULE</small></h4>
			        
					<%= render "partials/notification" %>
			        
			        <% if @showsubsched.count == 0 %>
			        	<div class="center">
			        		<h3 class="red-text center">No sub-schedules yet.</h3>
							<a href="#add_subsched" class="waves-effect waves-light btn-large blue modal-trigger">Click here</a> 
			        	</div>
					<% else %>
						<div class="row">
						    <% @showsubsched.each do |sub| %>
						        <div class="col s12 m6">  
							      <% if sub.ms_status == 1 %>
							      	<div class="collapsible-header green darken-2 white-text">
							      <% else %>
							      	<div class="collapsible-header red white-text">
							      <% end %> 

							    	<%= link_to sub.ms_day, {controller: "manila_students", action: "show_manila_students", id: sub.slug}, class: "white-text"%>
							    	<div class="right">
								      	<%= link_to material_icon.edit, {controller: "manila_sub_scheds", action: "edit", id: sub.id }, class: "white-text"%>  
							              
								      	<%= link_to material_icon.delete, {controller: "manila_sub_scheds", action: "destroy", id: sub.id}, :data => {confirm: "Do you want to delete this?"}, class: "white-text"%>  
							    	</div>
						        </div> 
						    <% end %>
					    </div> 
						<div class="fixed-action-btn"> 
							<a href="#add_subsched" class="waves-effect waves-light btn-floating btn-large blue modal-trigger"><%= material_icon.add %></a>
						</div> 
					<% end %>
				</div>
		  	</div>  
		</div> 
	<!-- Subschedule -->   

<div class="section">
	<div class="container center">
		<%= link_to "Main dashboard", admin_dashboard_path %> > 
		<%= link_to "Manila Dashboard", manila_dashboard_path %> > 
		<%= link_to @manilasched.duration, @manilasched.slug %> 
	</div>
</div>
	
<!-- Modal for New--> 
  <div id="add_subsched" class="modal modal-fixed-footer">
    <%= form_for @subschedule do |sub_sched| %> 
	    <div class="modal-content"> <!-- start of modal content -->
	      	<div class="row">
	      		<div class="col s1"></div>
	      		<div class="col s10">

	      			<h4 class="center">Add Sub Schedule for <br><span class="blue-text"><%= @manilasched.duration.upcase %></span></h4> 

				      <div class="row">
				        <div class="input-field col s6"> 
				          <%= sub_sched.hidden_field :manila_sched_id, :value => @manilasched.id, :class => "center" %>  
				        </div>
				        <div class="input-field col s6">
				          <%= sub_sched.hidden_field :admin_id, :value => current_user.id %>  
				        </div>
				      </div> 
				      <div class="row">
				        <div class="input-field col s3">
				          <%= sub_sched.label  :ms_slots, "Slots"%>
				          <%= sub_sched.text_field  :ms_slots, :class => "center"  %> 
				        </div>
				        <div class="input-field col s6">
				          <%= sub_sched.label  :ms_day, "Days"%>
				          <%= sub_sched.text_field  :ms_day, :class => "center"  %> 
				        </div>
				        <div class="input-field col s3">
				          <%= sub_sched.label  :ms_session, "Session"%>
				          <%= sub_sched.text_field  :ms_session, :class => "center"  %> 
				        </div>
				      </div>   
				      <div class="row">
				        <div class="input-field col s4">
				          <%= sub_sched.label  :ms_time, "Time"%>
				          <%= sub_sched.text_field  :ms_time, :class => "center"  %> 
				        </div>
				        <div class="input-field col s4">
				          <%= sub_sched.label  :ms_starts, "Class Starts"%>
				          <%= sub_sched.text_field  :ms_starts, :class => "center"  %> 
				        </div>
				        <div class="input-field col s4">
				          <%= sub_sched.label  :ms_jlpt_level, "JLPT Level"%>
				          <%= sub_sched.text_field :ms_jlpt_level, :class => "center"  %> 
				        </div>
				      </div>  
				      <div class="center">   
				          <%= sub_sched.label  :ms_status, "Status"%>
						    <%= sub_sched.radio_button(:ms_status, "0", :checked => true) %>
							<%= sub_sched.label(:ms_status_0, "Deactivate") %>
							<%= sub_sched.radio_button(:ms_status, "1") %>
							<%= sub_sched.label(:ms_status_1, "Activate") %>  
		              </div> 
	      			</div>   
	    				 
	      		<div class="col s1"></div> 
	      	</div>
    	</div><!--  End of modal content -->
		<div class="modal-footer">
	      <%= sub_sched.submit "Add Sub Schedule", :class => " modal-action modal-close waves-effect waves-light btn right" %> 
	    </div>  
	<% end %> 
  </div>
<!-- end of Modal for new-->