config/routes.rb
Rails.application.routes.draw do      
 
  resources :payment_terms
  root 'mains#index'

  # teacher
  get                  'admin/teachers'  => 'teachers#index'
  get              'admin/teachers/new'  => 'teachers#new'
  get          'admin/edit-teacher/:id'  => 'teachers#edit'
  get               'admin/teachers/:id' => 'teachers#destroy'

  get       'teachers/qualification/:id' => 'teacher_qualifications#destroy'
  get          'teachers/background/:id' => 'teacher_backgrounds#destroy'

  # sensei-preview
  get                           'sensei' => 'senseis#index'
  
  # inquiry
  get                  'admin/inquiries' => 'inquiries#show'
  get                          'inquiry' => 'inquiries#index'

  # manila
  get                 'manila/dashboard' => 'manilascheds#index'  
  get              'manila/new_schedule' => 'manilascheds#new'   
  get         'manila/edit-schedule/:id' => 'manilascheds#edit'
  patch     'manila/update-schedule/:id' => 'manilascheds#update'
  get       'manila/delete-schedule/:id' => 'manilascheds#destroy'

  # submanilasched
  get              'manila/schedule/:id' => 'manila_sub_scheds#new'  
  get         'manila/schedule/edit/:id' => 'manila_sub_scheds#edit'
  get     '  manila/schedule/delete/:id' => 'manila_sub_scheds#destroy' 
  patch     'manila/schedule/update/:id' => 'manila_sub_scheds#update'

  # manila students
  get 'manila-schedule/edit-student/:id' => 'manila_students#edit'    
  get         'manila-schedules/:id/:id' => 'manila_students#new'      
  get              'manila-students/:id' => 'manila_students#show_manila_students'
  get        'delete-manila-student/:id' => 'manila_students#destroy' 

  # cebu
  get                   'cebu/dashboard' => 'cebuscheds#index'  
  get                'cebu/new_schedule' => 'cebuscheds#new'   
  get           'cebu/edit-schedule/:id' => 'cebuscheds#edit'
  patch       'cebu/update-schedule/:id' => 'cebuscheds#update'
  get         'cebu/delete-schedule/:id' => 'cebuscheds#destroy' 

  # subcebusched
  get                'cebu/schedule/:id' => 'cebu_sub_scheds#new'  
  get           'cebu/schedule/edit/:id' => 'cebu_sub_scheds#edit'
  get         'cebu/schedule/delete/:id' => 'cebu_sub_scheds#destroy' 
  patch       'cebu/schedule/update/:id' => 'cebu_sub_scheds#update'

  # cebu students
  get           'cebu-students/edit/:id' => 'cebu_students#edit'    
  get           'cebu-schedules/:id/:id' => 'cebu_students#new'     
  get                'cebu-students/:id' => 'cebu_students#show_cebu_students'
  get          'delete-cebu-student/:id' => 'cebu_students#destroy' 

  # articles admin
  get                  'admin/articles/' => 'articles#index'
  get               'admin/articles/new' => 'articles#new'
  get               'admin/articles/:id' => 'articles#show'
  get          'admin/articles/:id/edit' => 'articles#edit'
  delete     'admin/articles/:id/delete' => 'articles#delete'
  mount                 Ckeditor::Engine => '/ckeditor'

  # articles main
  get                        '/articles' => 'main_articles#index'
  get                     'articles/:id' => 'main_articles#show'

  # main dashboards
  get                  'admin/dashboard' => 'dashboards#index'

  # main
  get                'all-payment-terms' => 'mains#payment_terms'
  get                   'cebu-schedules' => 'mains#cebuschedule'
  get               'cebu-schedules/:id' => 'mains#show_cebu'
  get                 'manila-schedules' => 'mains#manilaschedule'
  get             'manila-schedules/:id' => 'mains#show_manila'
  get              'reservation-success' => 'mains#success'
  get                  'student-gallery' => 'mains#gallery'
 
  # sessions
  get                           "logout" => "sessions#destroy"
  get                       'ncrs/login' => 'sessions#new'
  get                     'ncrs/sign_up' => 'admins#new'

  resources :sessions
  resources :admins 
  resources :password_resets 

  # teachers information
  resources :teachers
  resources :teacher_qualifications
  resources :teacher_backgrounds
  resources :senseis

  # articles
  resources :articles

  # gallery 
  resources :galleries

  # cebu
  resources :cebuscheds 
  resources :cebu_sub_scheds 

  # manila
  resources :manilascheds 
  resources :manila_sub_scheds 

  # inquiry
  resources :inquiries

  # cebu students
  resources :cebu_students

  # manila students
  resources :manila_students

  # main
  resources :mains
 
end

app/models/cebu_sched.rb
class CebuSched < ActiveRecord::Base
	belongs_to :admin
	has_many :cebu_sub_sched   

  extend FriendlyId 
	friendly_id :duration, use: :slugged  

   	def should_generate_new_friendly_id?
	    slug.blank? || self.duration_changed?
	end 
end

app/controllers/cebuscheds_controller.rb
class CebuschedsController < ApplicationController
  before_action :require_user 

  def index    
    @cebuscheds = CebuSched.where(:admin_id => current_user.id).order(created_at: :desc)
  end

  def show
    @showsched = CebuSched.friendly.find(params[:id])  
  end

  def new  
    @cebuschedule = CebuSched.new 
  end

  def create
  	@newschedule = CebuSched.new(cebusched_params)
  	if @newschedule.save!
  		redirect_to "/cebu/dashboard", :notice => "New Schedule Successfully Added"
  	else
  		redirect_to "/cebu/new_schedule", :notice => "Error on Adding New Schedule"
  	end
  end

  def edit    
    @updateschedule = CebuSched.friendly.find(params[:id])
  end  

  def update
    @updateSchedule = CebuSched.friendly.find(params[:id])
    if @updateSchedule.update_attributes(cebusched_params)
      redirect_to "/cebu/dashboard", :notice => "Schedule Updated Successfully"
    else
      redirect_to "/cebu/new_schedule/:id", :notice => "Updating Schedule Failed"
    end
  end 

  def destroy
    @deleteschedule = CebuSched.find(params[:id])
    if @deleteschedule.destroy
      redirect_to "/cebu/dashboard", :notice => "Schedule DeletedSuccessfully"
    else
      redirect_to "/cebu/dashboard", :notice => "Deleting Schedule Failed"
    end
  end   

  private

  def cebusched_params
    params.require(:cebu_sched).permit(:admin_id, :duration, :status, :slug)
  end
 
end

app/helpers/cebuscheds_helper.rb
module CebuschedsHelper
end

app/views/cebuscheds/edit.html.erb
<% provide(:title, "Edit Cebu Schedules |") %>
<%= render "layouts/navbar_admin" %>
<div class="container">
	<div class="section">
	<br>
	   	 <h4 class="center teal-text">Edit the Schedule</h4>
	      <div class="row">
		    <div class="col s2"></div>
		    <div class="col s8">

    		<%= form_for @updateschedule, url:{action: "update"}, html: {class: "form"} do |cs| %> 

				<%= render "partials/notification" %>

			      <div class="row">
			        <div class="input-field col s12">
			          <%= cs.hidden_field :admin_id, :value => @current_user.id %>  
			        </div>
			      </div>
			      <div class="row">
			        <div class="input-field col s12"> 
			          <%= cs.text_field :duration, :class => "center-align" %> 
			        </div>
			      </div> 
			      <div class="center">   
					    <%= cs.radio_button :status, "0", :checked => true %>
						<%= cs.label :status_0, "Deactivate" %>
						<%= cs.radio_button :status, "1" %>
						<%= cs.label :status_1, "Activate" %>  
	              </div> 
	              <br> 
	              	<%= cs.submit "update", :class => "modal-action waves-effect waves-light btn right" %> 
			<% end %>

		    </div>
		    <div class="col s2"></div>
		  </div> 
	</div>
</div>
 

app/views/cebuscheds/index.html.erb
<% provide(:title, "Cebu Schedules |") %>
<%= render "layouts/navbar_admin" %> 
<div class="container"> 
	<div class="section">      
	  	<h4 class="center">SCHEDULE LIBRARY</h4>

	  	<%= render "partials/notification" %>

	  	<% if @cebuscheds.count == 0 %>
			<h3 class="red-text center">No Schedules created yet!</h3>
			<p class="center"><%= link_to "Create now!", cebu_new_schedule_path, :class => "waves-effect waves-light btn-large blue" %></p>
		<% else %>
			<div class="row"> 
				<% @cebuscheds.each do |cs| %>
				  <div class="col s12 m4">
				  	<% if cs.status == 1 %>
				    	<div class="card teal darken-1 center-align">  
				  	<% else %> 
				    	<div class="card red darken-1 center-align">  
				  	<% end %>
				  		<div class="card-content">
				      	  <span class="card-title">
					      	<%= link_to cs.duration.upcase,{controller: "cebu_sub_scheds", action: "new", id: cs.slug}, :class => "white-text"%>
					      </span> 
					      <p class="white-text">Created: <%= time_ago_in_words(cs.created_at) %> ago</p>
				  		</div> 
				  		<div class="card-action"> 
						    <%= link_to material_icon.edit, {controller: "cebuscheds", action: "edit", id: cs.slug}, :class => "white-text"%>  
					      	<%= link_to material_icon.delete, {controller: "cebuscheds", action: "destroy", id: cs.id}, :data => {confirm: "Do you want to delete this?"}, :class => "white-text"%> 
				  		</div>
				  </div> 
				<% end %>
			</div>
		<% end %>
		<div class="fixed-action-btn">
			<%= link_to material_icon.add, cebu_new_schedule_path, :class => "waves-effect waves-light btn-floating btn-large blue"%> 
		</div>  
	</div>
</div>

<div class="section">
	<div class="container center">
		<%= link_to "Main dashboard", admin_dashboard_path %> > 
		<%= link_to "Cebu Dashboard", cebu_dashboard_path %>
	</div>
</div>

app/views/cebuscheds/new.html.erb
<% provide(:title, "Add Cebu Schedule") %>
<%= render "layouts/navbar_admin" %>
<div class="container">
	<div class="section">
	<br>
	   	 <h4 class="center teal-text">Add New Sched</h4>
	      <div class="row">
		    <div class="col s2"></div>
		    <div class="col s8">

    		<%= form_for @cebuschedule, url:{action: "create"}, html: {class: "form"} do |cs| %> 

				<%= render "partials/notification" %>

			      <div class="row">
			        <div class="input-field col s12">
			          <%= cs.hidden_field :admin_id, :value => @current_user.id %>  
			        </div>
			      </div>
			      <div class="row">
			        <div class="input-field col s12">
			          <%= cs.label :duration, "From and to"%>
			          <%= cs.text_field :duration, :class => "center-align" %> 
			        </div>
			      </div> 
			      <div class="center">   
					    <%= cs.radio_button :status, "0", :checked => true %>
						<%= cs.label :status_0, "Deactivate" %>
						<%= cs.radio_button :status, "1" %>
						<%= cs.label :status_1, "Activate" %>  
	              </div> 
	              <br> 
	              	<%= cs.submit "Create", :class => "modal-action waves-effect waves-light btn right" %> 
			<% end %>

		    </div>
		    <div class="col s2"></div>
		  </div> 
	</div>
</div>
 