config/routes.rb
Rails.application.routes.draw do      
 
  resources :payment_terms
  root 'mains#index'

  # teacher
  get                  'admin/teachers'  => 'teachers#index'
  get              'admin/teachers/new'  => 'teachers#new'
  get          'admin/edit-teacher/:id'  => 'teachers#edit'
  get               'admin/teachers/:id' => 'teachers#destroy'

  get       'teachers/qualification/:id' => 'teacher_qualifications#destroy'
  get          'teachers/background/:id' => 'teacher_backgrounds#destroy'

  # sensei-preview
  get                           'sensei' => 'senseis#index'
  
  # inquiry
  get                  'admin/inquiries' => 'inquiries#show'
  get                          'inquiry' => 'inquiries#index'

  # manila
  get                 'manila/dashboard' => 'manilascheds#index'  
  get              'manila/new_schedule' => 'manilascheds#new'   
  get         'manila/edit-schedule/:id' => 'manilascheds#edit'
  patch     'manila/update-schedule/:id' => 'manilascheds#update'
  get       'manila/delete-schedule/:id' => 'manilascheds#destroy'

  # submanilasched
  get              'manila/schedule/:id' => 'manila_sub_scheds#new'  
  get         'manila/schedule/edit/:id' => 'manila_sub_scheds#edit'
  get     '  manila/schedule/delete/:id' => 'manila_sub_scheds#destroy' 
  patch     'manila/schedule/update/:id' => 'manila_sub_scheds#update'

  # manila students
  get 'manila-schedule/edit-student/:id' => 'manila_students#edit'    
  get         'manila-schedules/:id/:id' => 'manila_students#new'      
  get              'manila-students/:id' => 'manila_students#show_manila_students'
  get        'delete-manila-student/:id' => 'manila_students#destroy' 

  # cebu
  get                   'cebu/dashboard' => 'cebuscheds#index'  
  get                'cebu/new_schedule' => 'cebuscheds#new'   
  get           'cebu/edit-schedule/:id' => 'cebuscheds#edit'
  patch       'cebu/update-schedule/:id' => 'cebuscheds#update'
  get         'cebu/delete-schedule/:id' => 'cebuscheds#destroy' 

  # subcebusched
  get                'cebu/schedule/:id' => 'cebu_sub_scheds#new'  
  get           'cebu/schedule/edit/:id' => 'cebu_sub_scheds#edit'
  get         'cebu/schedule/delete/:id' => 'cebu_sub_scheds#destroy' 
  patch       'cebu/schedule/update/:id' => 'cebu_sub_scheds#update'

  # cebu students
  get           'cebu-students/edit/:id' => 'cebu_students#edit'    
  get           'cebu-schedules/:id/:id' => 'cebu_students#new'     
  get                'cebu-students/:id' => 'cebu_students#show_cebu_students'
  get          'delete-cebu-student/:id' => 'cebu_students#destroy' 

  # articles admin
  get                  'admin/articles/' => 'articles#index'
  get               'admin/articles/new' => 'articles#new'
  get               'admin/articles/:id' => 'articles#show'
  get          'admin/articles/:id/edit' => 'articles#edit'
  delete     'admin/articles/:id/delete' => 'articles#delete'
  mount                 Ckeditor::Engine => '/ckeditor'

  # articles main
  get                        '/articles' => 'main_articles#index'
  get                     'articles/:id' => 'main_articles#show'

  # main dashboards
  get                  'admin/dashboard' => 'dashboards#index'

  # main
  get                'all-payment-terms' => 'mains#payment_terms'
  get                   'cebu-schedules' => 'mains#cebuschedule'
  get               'cebu-schedules/:id' => 'mains#show_cebu'
  get                 'manila-schedules' => 'mains#manilaschedule'
  get             'manila-schedules/:id' => 'mains#show_manila'
  get              'reservation-success' => 'mains#success'
  get                  'student-gallery' => 'mains#gallery'
 
  # sessions
  get                           "logout" => "sessions#destroy"
  get                       'ncrs/login' => 'sessions#new'
  get                     'ncrs/sign_up' => 'admins#new'

  resources :sessions
  resources :admins 
  resources :password_resets 

  # teachers information
  resources :teachers
  resources :teacher_qualifications
  resources :teacher_backgrounds
  resources :senseis

  # articles
  resources :articles

  # gallery 
  resources :galleries

  # cebu
  resources :cebuscheds 
  resources :cebu_sub_scheds 

  # manila
  resources :manilascheds 
  resources :manila_sub_scheds 

  # inquiry
  resources :inquiries

  # cebu students
  resources :cebu_students

  # manila students
  resources :manila_students

  # main
  resources :mains
 
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :require_user 

  def index
  	@teachers = TeacherInformation.all  
  	@qualification = TeacherQualification.all
  	@background = TeacherBackground.all

  	@teachers_qualification = TeacherQualification.new
  	@teachers_background = TeacherBackground.new
  end

  def new
  	@teachers = TeacherInformation.new
  end

  def create
  	@teachers = TeacherInformation.new(teacher_information_params)
  	if @teachers.save
  		redirect_to admin_teachers_path, notice: "Successfully added new teacher."
  	else
  		render "new"
  	end
  end

  def create_background
  	@teachers_background = TeacherBackground.new(teacher_background_params)
  	if @teachers_background.save!
  		redirect_to admin_teachers_path
  	else
  		redirect_to admin_teachers_path
  	end
  end

  def edit
  	@edit_teacher = TeacherInformation.find(params[:id])
  end

  def update
  	@update_teacher = TeacherInformation.find(params[:id])
  	if @update_teacher.update_attributes(teacher_information_params)
  		redirect_to admin_teachers_path, notice: "Successfully Edited teacher."
  	else
  		redirect_to admin_teachers_path, notice: "Error updating teacher."
  	end
  end

  def destroy
  	@delete_teacher = TeacherInformation.find(params[:id])
  		if @delete_teacher.destroy
  			redirect_to admin_teachers_path, notice: "Successfully deleted teacher."
  		else
  			redirect_to admin_teachers_path, notice: "Deleting unsuccessful."
  		end
  end

  private
  def teacher_information_params
  	params.require(:teacher_information).permit(:name, :age, :address, :emailaddress, :contact_number, :image, :branch, :branch_address)
  end 
  
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/edit.html.erb
<% provide(:title, "Edit Teacher |") %>
<%= render "layouts/navbar_admin" %>
<div class="container">  

	<div class="card">
		<div class="card-content">
			<%= form_for @edit_teacher, url:{action: "update"}, html: { multipart: true, class: "form" } do |f|%>
				<div class="row">

				    <div class="col s12 m4 file-field input-field">
				      <div class="btn">
				        <span>Upload Image</span>
				        <input type="file">
				      </div>
				      <div class="file-path-wrapper">
						<%= f.file_field :image, as: :file %> 
				      </div>
				    </div> 

					<div class="col s12 m8"> 
						
						<div class="row">
							<div class="input-field col s12">
								<%= f.label :name %>
								<%= f.text_field :name %>
							</div>
						</div>
						
						<div class="row">
							<div class="input-field col s12">
								<%= f.label :age %>
								<%= f.text_field :age %>
							</div>
						</div>
						
						<div class="row">
							<div class="input-field col s12">
								<%= f.label :address %>
								<%= f.text_field :address %>
							</div>
						</div>
						
						<div class="row">
							<div class="input-field col s12">
								<%= f.label :emailaddress %>
								<%= f.email_field :emailaddress %>
							</div>
						</div>
						
						<div class="row">
							<div class="input-field col s12">
								<%= f.label :contact_number %>
								<%= f.text_field :contact_number %>
							</div>
						</div>
						
						<div class="row">
							<div class="input-field col s12">
								<%= f.label :branch %>
								<%= f.text_field :branch %>
							</div>
						</div>

						<div class="row">
							<div class="input-field col s12">
								<%= f.label :branch_address, "Branch Address" %>
								<%= f.text_field :branch_address %>
							</div>
						</div>

							<%= f.submit "Update", class: "waves-effect btn blue" %>

					</div>
				</div>
			<% end %>
		</div>
	</div>

</div>

app/views/teachers/index.html.erb
<% provide(:title, "Teachers |") %>
<%= render "layouts/navbar_admin" %>
<div class="container"> 
	
	<%= render "partials/notification" %>

	<% if @teachers.count == 0 %>
		<h4 class="blue-text center">No Current Teacher added!</h4>
	<% else %>
		<% @teachers.each do |teacher| %>
			<div class="card">
				<div class="card-content">
					<div class="row">	  					
						<div class="col s12 m4">
							<%= image_tag teacher.image.url(:medium) %>
							<div class="center">
								<%= link_to material_icon.edit, {controller: "teachers", action: "edit", id: teacher.id}, class: "blue-text"%>

								<%= link_to material_icon.delete, {controller: "teachers", action: "destroy", id: teacher.id}, data: { confirm: 'Are you sure you wanna delete this?' }, class: "red-text"%>
							</div>
						</div>
						<div class="col s12 m8">

							<h5 class="blue-text center">Personal Information</h5>
							<p> 
								<strong>Name:</strong> 	<%= teacher.name %> <br>
								<strong>Age:</strong> 	<%= teacher.age %>  <br>
								<strong>Address:</strong> 	<%= teacher.address %> <br>
								<strong>Email Address:</strong> 	<%= teacher.emailaddress %> <br>
								<strong>Contact:</strong> 	<%= teacher.contact_number %> <br>
								<strong>Branch:</strong> 	<%= teacher.branch.capitalize %><br>
								<strong>Branch Address:</strong> 	<%= teacher.branch_address %>
							</p>

							<div class="divider"></div>

							<h5 class="blue-text center">Qualifications</h5> 
 
							<div id="qualification">
								<%= form_for @teachers_qualification do |q|%>
								    <div class="row">
								    	<%= q.hidden_field :teacher_information_id, value: teacher.id %>
								    	<div class="col s1"></div>
								        <div class="input-field col s8">
								          <%= q.text_field :qualification %>
								        </div>
								        <div class="input-field col s2">
								          <%= q.submit "Add", class: "waves-effect btn blue"%>
								    	</div>  
								    	<div class="col s1"></div>
								    </div>
							    <% end %> 
							</div>  

							<% @qualification.each do |qualify| %>
								<% if teacher.id == qualify.teacher_information_id %> 
									<p>
										<strong><%= qualify.qualification%></strong> 
										<small>
											<%= link_to material_icon.delete, {controller: "teacher_qualifications", action: "destroy", id: qualify.id}, :data => {confirm: "Do you want to delete this?"}, :class => "grey-text"%>  
										</small>
									</p>
									<div class="divider"></div> 
								<% end %>
							<% end %>  

							<div class="divider"></div>

							<h5 class="blue-text center">Background</h5>
 
						    <%= form_for @teachers_background do |q|%>
							    <div class="row">
							    	<%= q.hidden_field :teacher_information_id, value: teacher.id %>
							    	<div class="col s1"></div>
							        <div class="input-field col s8 ">
							          <%= q.text_field :background %>
							        </div>
							        <div class="input-field col s2">
							          <%= q.submit "Add", class: "waves-effect btn blue"%>
							    	</div>  
							    	<div class="col s1"></div>
							    </div>
						    <% end %>  

							<% @background.each do |bg| %>
								<% if teacher.id == bg.teacher_information_id %> 
									<p>
										<strong><%= bg.background%></strong> 
										<small>
											<%= link_to material_icon.delete, {controller: "teacher_backgrounds", action: "destroy", id: bg.id}, :data => {confirm: "Do you want to delete this?"}, :class => "grey-text"%>  
										</small>
									</p>
									<div class="divider"></div> 
								<% end %>
							<% end %> 

						</div>

					</div>
				</div>
			</div>
		<% end %>
	<% end %>

	<div class="fixed-action-btn">
		<%= link_to material_icon.add, admin_teachers_new_path, :class => "waves-effect waves-light btn-floating btn-large blue"%> 
	</div>   
</div> 



  

app/views/teachers/new.html.erb
<% provide(:title, "Add Teacher |") %>
<%= render "layouts/navbar_admin" %>
<div class="container">  

	<div class="card">
		<div class="card-content">

		    <% if @teachers.errors.any? %>
		      <div class="error_messages"> 
		        <ul class="center">
		          <% for message in @teachers.errors.full_messages %>
		            <li class="red-text"><%= message %></li>
		          <% end %>
		        </ul>
		      </div>
		    <% end %>

			<%= form_for @teachers, url:{action: "create"}, html: { multipart: true, class: "form" } do |f|%>
				<div class="row">

				    <div class="col s12 m4 file-field input-field">
				      <div class="btn">
				        <span>Upload Image</span>
				        <input type="file">
				      </div>
				      <div class="file-path-wrapper">
						<%= f.file_field :image %>
				      </div>
				    </div> 

					<div class="col s12 m8">
						
						<div class="row">
							<div class="input-field col s12">
								<%= f.label :name %>
								<%= f.text_field :name %>
							</div>
						</div>
						
						<div class="row">
							<div class="input-field col s12">
								<%= f.label :age %>
								<%= f.text_field :age %>
							</div>
						</div>
						
						<div class="row">
							<div class="input-field col s12">
								<%= f.label :address %>
								<%= f.text_field :address %>
							</div>
						</div>
						
						<div class="row">
							<div class="input-field col s12">
								<%= f.label :emailaddress %>
								<%= f.email_field :emailaddress %>
							</div>
						</div>
						
						<div class="row">
							<div class="input-field col s12">
								<%= f.label :contact_number %>
								<%= f.text_field :contact_number %>
							</div>
						</div>
						
						<div class="row">
							<div class="input-field col s12">
								<%= f.label :branch %>
								<%= f.text_field :branch %>
							</div>
						</div>

						<div class="row">
							<div class="input-field col s12">
								<%= f.label :branch_address, "Branch Address" %>
								<%= f.text_field :branch_address %>
							</div>
						</div>

							<%= f.submit "Create New", class: "waves-effect btn blue" %>

					</div>
				</div>
			<% end %>
		</div>
	</div>

</div>